#!/bin/bash
set -e
echo "running subinstalls" >&2
(cd libs && make install)
declare -i indep=0
test -f "$installabs/lib64/lib$current_lib.so" || indep=1
echo "ensuring ${installdir}/lib64 exists"
mkdir -p -v "$installabs"/lib64
echo "creating -l$current_lib inside ${installdir}/lib64"
cp --preserve=timestamps -u -v -- libs/.shared.so "$installabs"/lib64/lib$current_lib.so
cp --preserve=timestamps -u -v -- libs/.static.a "$installabs"/lib64/lib$current_lib.a
ln -snfv "${installabs}/include" libs/include
shopt -s nullglob
declare -a rules=(.*.mk)
declare -a files=(*.o)
if ((indep)); then
	if ((${#rules[@]})); then
		echo "removing test .*.mk files, as installation modifies dependency sources"
		rm -v -- "${rules[@]}"
	fi
	if ((${#files[@]})); then
		echo "removing test *.o files, as installation modifies shared libary origin";
		rm -v -- "${files[@]}"
	fi
fi
if ((${#files[@]})); then
	echo "re-making test *.o files, as the installation directory has been potentially updated"
	MAKELEVEL=$((MAKELEVEL - 1)) make -- "${files[@]}"
fi
